### ISSUE TITLE
gcc7 format-truncation error

### ISSUE THREAD

**Issue by grighi** [WizardMac/ReadStat#97]
when attempting to build with gcc 7.1.1 on arch linux I get:

  ```
CC       src/sas/libreadstat_la-readstat_sas.lo
src/sas/readstat_sas.c: In function ‘sas_write_header’:
src/sas/readstat_sas.c:304:14: error: ‘%1ld’ directive output may be truncated writing between 1 and 16 bytes into a region of size 8 [-Werror=format-truncation=]
             "%1ld.%04ldM0", writer->version / 10000, writer->version % 10000);
              ^~~~
src/sas/readstat_sas.c:304:13: note: directive argument in the range [-922337203685477, 922337203685477]
             "%1ld.%04ldM0", writer->version / 10000, writer->version % 10000);
             ^~~~~~~~~~~~~~
src/sas/readstat_sas.c:304:13: note: directive argument in the range [-9999, 9999]
src/sas/readstat_sas.c:303:5: note: ‘snprintf’ output between 9 and 25 bytes into a destination of size 8
     snprintf(header_end.release, sizeof(header_end.release),
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             "%1ld.%04ldM0", writer->version / 10000, writer->version % 10000);
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:1410: src/sas/libreadstat_la-readstat_sas.lo] Error 1
```

**Comment by evanmiller** [comment]
Fixed in https://github.com/WizardMac/ReadStat/commit/05f2d5851f2858ce93d548ce9828d667742f2b4d
