### ISSUE TITLE
Several `-Werror=format-truncation` errors when building with modern GCC

### ISSUE THREAD

**Issue by Keno** [WizardMac/ReadStat#100]
```
src/spss/readstat_spss.c: In function ‘spss_init_variable_for_info’:
src/spss/readstat_spss.c:139:58: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
         snprintf(variable->name, sizeof(variable->name), "%s", info->longname);
                                                          ^~~~
src/spss/readstat_spss.c:139:9: note: ‘snprintf’ output between 1 and 257 bytes into a destination of size 256
         snprintf(variable->name, sizeof(variable->name), "%s", info->longname);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/sas/readstat_sas7bdat_read.c: In function ‘sas7bdat_init_variable’:
src/sas/readstat_sas7bdat_read.c:517:101: error: ‘%s’ directive output may be truncated writing up to 1023 bytes into a region of size between 435 and 954 [-Werror=format-truncation=]
                         "ReadStat: Error converting variable #%d info to specified encoding: %s %s (%s)\n",
                                                                                                     ^~
src/sas/readstat_sas7bdat_read.c:516:17: note: ‘snprintf’ output between 73 and 1615 bytes into a destination of size 1024
                 snprintf(error_buf, sizeof(error_buf),
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                         "ReadStat: Error converting variable #%d info to specified encoding: %s %s (%s)\n",
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                         i, variable->name, variable->format, variable->label);
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/sas/readstat_xport_write.c: In function ‘xport_begin_data’:
src/sas/readstat_xport_write.c:339:13: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
             "%02d"       "%3s"              "%02d"             ":%02d:%02d:%02d",
             ^~~~~~
src/sas/readstat_xport_write.c:338:5: note: ‘snprintf’ output 17 or more bytes (assuming 18) into a destination of size 17
     snprintf(timestamp, sizeof(timestamp),
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             "%02d"       "%3s"              "%02d"             ":%02d:%02d:%02d",
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             ts->tm_mday, _xport_months[ts->tm_mon], ts->tm_year % 100, ts->tm_hour, ts->tm_min, ts->tm_sec);
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/sas/readstat_xport_write.c:306:13: error: ‘%-40s’ directive output may be truncated writing between 40 and 99 bytes into a region of size 49 [-Werror=format-truncation=]
             "%16s"     "%16s"  "%-40s"              "%-8s",
             ^~~~~~
src/sas/readstat_xport_write.c:306:33: note: format string is defined here
             "%16s"     "%16s"  "%-40s"              "%-8s",
                                 ^~~~~
src/sas/readstat_xport_write.c:305:5: note: ‘snprintf’ output 81 or more bytes (assuming 140) into a destination of size 81
     snprintf(member_header, sizeof(member_header),
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             "%16s"     "%16s"  "%-40s"              "%-8s",
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             timestamp, "",     writer->file_label,  "" /* dstype? */);
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
There may be others. GCC version:

```
bash-4.3# gcc --version
gcc (GCC) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Building with `CFLAGS="-Wno-error=format-truncation"` works as a temporary workaround.

**Comment by evanmiller** [comment]
Thanks. I'm not too excited about fixing these individually because getting GCC 7.2 on Travis will be a bit of work. On the other hand, the amount of autoconf crap required to conditionally insert that flag seems like even more of a pain. I'll try to get them fixed and just hope new warnings aren't introduced until GCC 7.2 is available on Travis.

**Comment by evanmiller** [comment]
Hi, see if this fixes things: https://github.com/WizardMac/ReadStat/commit/b0db3b768de35ec7d7c0c864461c44942b7baa64

Still working on installing GCC 7.2 on my local system...

**Comment by Keno** [comment]
```
src/sas/readstat_xport_write.c: In function ‘xport_begin_data’:
src/sas/readstat_xport_write.c:337:10: error: ‘snprintf’ output truncated before the last format character [-Werror=format-truncation=]
     p += snprintf(p, 2, "%02d", ts->tm_mday);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/sas/readstat_xport_write.c:337:10: note: ‘snprintf’ output between 3 and 12 bytes into a destination of size 2
src/sas/readstat_xport_write.c:338:10: error: ‘snprintf’ output truncated before the last format character [-Werror=format-truncation=]
     p += snprintf(p, 3, "%3.3s", _xport_months[ts->tm_mon]);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/sas/readstat_xport_write.c:338:10: note: ‘snprintf’ output 4 bytes into a destination of size 3
src/sas/readstat_xport_write.c:339:10: error: ‘snprintf’ output truncated before the last format character [-Werror=format-truncation=]
     p += snprintf(p, 2, "%02d", ts->tm_year % 100);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/sas/readstat_xport_write.c:339:10: note: ‘snprintf’ output between 3 and 4 bytes into a destination of size 2
src/sas/readstat_xport_write.c:340:10: error: ‘snprintf’ output truncated before the last format character [-Werror=format-truncation=]
     p += snprintf(p, 3, ":%02d", ts->tm_hour);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/sas/readstat_xport_write.c:340:10: note: ‘snprintf’ output between 4 and 13 bytes into a destination of size 3
src/sas/readstat_xport_write.c:341:10: error: ‘snprintf’ output truncated before the last format character [-Werror=format-truncation=]
     p += snprintf(p, 3, ":%02d", ts->tm_min);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/sas/readstat_xport_write.c:341:10: note: ‘snprintf’ output between 4 and 13 bytes into a destination of size 3
src/sas/readstat_xport_write.c:342:10: error: ‘snprintf’ output truncated before the last format character [-Werror=format-truncation=]
     p += snprintf(p, 3, ":%02d", ts->tm_sec);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/sas/readstat_xport_write.c:342:10: note: ‘snprintf’ output between 4 and 13 bytes into a destination of size 3
cc1: all warnings being treated as errors
make: *** [Makefile:1466: src/sas/libreadstat_la-readstat_xport_write.lo] Error 1
make: *** Waiting for unfinished jobs....
src/spss/readstat_sav_write.c: In function ‘sav_begin_data’:
src/spss/readstat_sav_write.c:601:52: error: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 6 [-Werror=format-truncation=]
         snprintf(name_data, sizeof(name_data), "VAR%d", i);
                                                    ^~
src/spss/readstat_sav_write.c:601:48: note: directive argument in the range [0, 2147483647]
         snprintf(name_data, sizeof(name_data), "VAR%d", i);
                                                ^~~~~~~
src/spss/readstat_sav_write.c:601:9: note: ‘snprintf’ output between 5 and 14 bytes into a destination of size 9
         snprintf(name_data, sizeof(name_data), "VAR%d", i);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/spss/readstat_sav_write.c:629:56: error: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 6 [-Werror=format-truncation=]
             snprintf(name_data, sizeof(name_data), "VAR%d", i);
                                                        ^~
src/spss/readstat_sav_write.c:629:52: note: directive argument in the range [0, 2147483647]
             snprintf(name_data, sizeof(name_data), "VAR%d", i);
                                                    ^~~~~~~
src/spss/readstat_sav_write.c:629:13: note: ‘snprintf’ output between 5 and 14 bytes into a destination of size 9
             snprintf(name_data, sizeof(name_data), "VAR%d", i);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/spss/readstat_sav_write.c:687:51: error: ‘%05d’ directive output may be truncated writing between 5 and 11 bytes into a region of size between 1 and 10 [-Werror=format-truncation=]
         snprintf(kv_data, sizeof(kv_data), "VAR%d=%05d",
                                                   ^~~~
src/spss/readstat_sav_write.c:687:44: note: using the range [-2147483648, 2147483647] for directive argument
         snprintf(kv_data, sizeof(kv_data), "VAR%d=%05d",
                                            ^~~~~~~~~~~~
src/spss/readstat_sav_write.c:687:9: note: ‘snprintf’ output between 11 and 26 bytes into a destination of size 15
         snprintf(kv_data, sizeof(kv_data), "VAR%d=%05d",
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 i, (int)r_variable->user_width);
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/spss/readstat_sav_write.c:706:51: error: ‘%05d’ directive output may be truncated writing between 5 and 11 bytes into a region of size between 1 and 10 [-Werror=format-truncation=]
         snprintf(kv_data, sizeof(kv_data), "VAR%d=%05d",
                                                   ^~~~
src/spss/readstat_sav_write.c:706:44: note: using the range [-2147483648, 2147483647] for directive argument
         snprintf(kv_data, sizeof(kv_data), "VAR%d=%05d",
                                            ^~~~~~~~~~~~
src/spss/readstat_sav_write.c:706:9: note: ‘snprintf’ output between 11 and 26 bytes into a destination of size 15
         snprintf(kv_data, sizeof(kv_data), "VAR%d=%05d",
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 i, (int)r_variable->user_width);
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

If you're on a linux system, https://github.com/JuliaPackaging/BinaryBuilder.jl comes with GCC 7.2 (`using BinaryBuilder; BinaryBuilder.run_wizard()` (different kind of Wizard)).

**Comment by evanmiller** [comment]
Thanks. I'm working on a Mac, installing GCC 7.2 now.

**Comment by evanmiller** [comment]
Ok, still don't have 7.2 on my local machine, but it's up and running on Travis now. I'll plow through until the warnings are fixed and then close the issue.

**Comment by evanmiller** [comment]
All seem to be fixed now. Please open a new issue if you continue to experience build errors.

**Comment by Keno** [comment]
Still seeing
```
src/spss/readstat_sav_write.c: In function ‘sav_begin_data’:
src/spss/readstat_sav_write.c:61:38: error: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 6 [-Werror=format-truncation=]
     snprintf(output, output_len, "VAR%d", i);
                                      ^~
src/spss/readstat_sav_write.c:61:34: note: directive argument in the range [0, 2147483647]
     snprintf(output, output_len, "VAR%d", i);
                                  ^~~~~~~
src/spss/readstat_sav_write.c:61:5: note: ‘snprintf’ output between 5 and 14 bytes into a destination of size 9
     snprintf(output, output_len, "VAR%d", i);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/spss/readstat_sav_write.c:61:38: error: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 6 [-Werror=format-truncation=]
     snprintf(output, output_len, "VAR%d", i);
                                      ^~
src/spss/readstat_sav_write.c:61:34: note: directive argument in the range [0, 2147483647]
     snprintf(output, output_len, "VAR%d", i);
                                  ^~~~~~~
src/spss/readstat_sav_write.c:61:5: note: ‘snprintf’ output between 5 and 14 bytes into a destination of size 9
     snprintf(output, output_len, "VAR%d", i);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/spss/readstat_sav_write.c:61:38: error: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 6 [-Werror=format-truncation=]
     snprintf(output, output_len, "VAR%d", i);
                                      ^~
src/spss/readstat_sav_write.c:61:34: note: directive argument in the range [0, 2147483647]
     snprintf(output, output_len, "VAR%d", i);
                                  ^~~~~~~
src/spss/readstat_sav_write.c:61:5: note: ‘snprintf’ output between 5 and 14 bytes into a destination of size 9
     snprintf(output, output_len, "VAR%d", i);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/spss/readstat_sav_write.c:61:38: error: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 6 [-Werror=format-truncation=]
     snprintf(output, output_len, "VAR%d", i);
                                      ^~
src/spss/readstat_sav_write.c:61:34: note: directive argument in the range [0, 2147483647]
     snprintf(output, output_len, "VAR%d", i);
                                  ^~~~~~~
src/spss/readstat_sav_write.c:61:5: note: ‘snprintf’ output between 5 and 14 bytes into a destination of size 9
     snprintf(output, output_len, "VAR%d", i);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by evanmiller** [comment]
Thanks. That warning is quite aggressive. Try this:

https://github.com/WizardMac/ReadStat/commit/f6bfe845689abc6f251acedd1c873cc86e1fdd5c

**Comment by Keno** [comment]
Seems to go through! Thanks!
